# Generated by Django 4.2.23 on 2026-01-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_clube_id_alter_competicao_id_alter_gol_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalacao',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escalacao',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
