# Generated by Django 5.2.10 on 2026-01-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_escalacao_x_escalacao_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desempenho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('gols', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='backend.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='backend.partida')),
            ],
            options={
                'verbose_name': 'Desempenho',
                'unique_together': {('partida', 'jogador')},
            },
        ),
    ]
