# Generated by Django 5.2.10 on 2026-02-28 21:01

import backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_clube_data_criacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='desempenho',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='escalacao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='competicao',
            name='competicao_destino',
        ),
        migrations.RemoveField(
            model_name='competicao',
            name='garante_vaga',
        ),
        migrations.RemoveField(
            model_name='competicao',
            name='tem_premiacao_financeira',
        ),
        migrations.RemoveField(
            model_name='competicao',
            name='tem_trofeu',
        ),
        migrations.RemoveField(
            model_name='competicao',
            name='valor_premiacao',
        ),
        migrations.RemoveField(
            model_name='gol',
            name='id',
        ),
        migrations.AddField(
            model_name='desempenho',
            name='cartao_amarelo',
            field=models.IntegerField(db_column='cartao_amarelo_desempenho', default=0),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='cartao_vermelho',
            field=models.IntegerField(db_column='cartao_vermelho_desempenho', default=0),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='minutos_jogados',
            field=models.IntegerField(blank=True, db_column='minutos_jogados_desempenho', null=True),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='pk',
            field=models.CompositePrimaryKey('partida', 'jogador', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='escalacao',
            name='pk',
            field=models.CompositePrimaryKey('partida', 'jogador', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gol',
            name='pk',
            field=models.CompositePrimaryKey('autor', 'partida', 'minuto', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='data_criacao',
            field=models.DateField(blank=True, db_column='data_fundacao_clube', null=True),
        ),
        migrations.AlterField(
            model_name='clube',
            name='escudo',
            field=models.ImageField(blank=True, db_column='escudo_clube', null=True, upload_to='escudos/'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='id',
            field=models.CharField(db_column='id_clube', default=backend.models.generate_clube_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='nome',
            field=models.CharField(db_column='nome_clube', max_length=100),
        ),
        migrations.AlterField(
            model_name='clube',
            name='pais',
            field=models.CharField(db_column='pais_clube', max_length=100),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='divisao',
            field=models.CharField(blank=True, db_column='divisao_competicao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='id',
            field=models.CharField(db_column='id_competicao', default=backend.models.generate_competicao_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='localidade',
            field=models.CharField(blank=True, db_column='localidade_competicao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='nome',
            field=models.CharField(db_column='nome_competicao', max_length=100),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='qtd_participantes',
            field=models.IntegerField(db_column='qtd_participantes_competicao', default=0),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='tamanho',
            field=models.CharField(db_column='abrangencia_competicao', max_length=100),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='tipo_formato',
            field=models.CharField(blank=True, db_column='tipo_formato_competicao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='tipo_participantes',
            field=models.CharField(db_column='tipo_participantes_competicao', max_length=100),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='assistencias',
            field=models.IntegerField(db_column='assistencia_desempenho', default=0),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='gols',
            field=models.IntegerField(db_column='gol_desempenho', default=0),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='jogador',
            field=models.ForeignKey(db_column='id_jogador', on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='backend.jogador'),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='nota',
            field=models.DecimalField(db_column='nota_desempenho', decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='partida',
            field=models.ForeignKey(db_column='id_partida', on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='backend.partida'),
        ),
        migrations.AlterField(
            model_name='escalacao',
            name='jogador',
            field=models.ForeignKey(db_column='id_jogador', on_delete=django.db.models.deletion.CASCADE, related_name='escalacoes', to='backend.jogador'),
        ),
        migrations.AlterField(
            model_name='escalacao',
            name='partida',
            field=models.ForeignKey(db_column='id_partida', on_delete=django.db.models.deletion.CASCADE, related_name='escalacoes', to='backend.partida'),
        ),
        migrations.AlterField(
            model_name='escalacao',
            name='status',
            field=models.CharField(choices=[('TITULAR', 'Titular'), ('RESERVA', 'Reserva')], db_column='status_escalacao', max_length=50),
        ),
        migrations.AlterField(
            model_name='escalacao',
            name='x',
            field=models.FloatField(blank=True, db_column='coord_x_escalacao', null=True),
        ),
        migrations.AlterField(
            model_name='escalacao',
            name='y',
            field=models.FloatField(blank=True, db_column='coord_y_escalacao', null=True),
        ),
        migrations.AlterField(
            model_name='gol',
            name='assistencia',
            field=models.ForeignKey(blank=True, db_column='id_jogador_assistencia_gol', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistencias_feitas', to='backend.jogador'),
        ),
        migrations.AlterField(
            model_name='gol',
            name='autor',
            field=models.ForeignKey(db_column='id_jogador', on_delete=django.db.models.deletion.CASCADE, related_name='gols_marcados', to='backend.jogador'),
        ),
        migrations.AlterField(
            model_name='gol',
            name='minuto',
            field=models.IntegerField(db_column='minuto_gol', default=0, help_text='Minuto do gol'),
        ),
        migrations.AlterField(
            model_name='gol',
            name='partida',
            field=models.ForeignKey(db_column='id_partida', on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='backend.partida'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='altura',
            field=models.IntegerField(blank=True, db_column='altura_jogador', null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='clube',
            field=models.ForeignKey(blank=True, db_column='id_clube', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores', to='backend.clube'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='cpf',
            field=models.CharField(db_column='cpf_jogador', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='data_nascimento',
            field=models.DateField(blank=True, db_column='data_nascimento_jogador', null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, db_column='foto_jogador', null=True, upload_to='jogadores/'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id',
            field=models.CharField(db_column='id_jogador', default=backend.models.generate_jogador_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nacionalidade',
            field=models.CharField(db_column='nacionalidade_jogador', max_length=100),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.CharField(db_column='nome_jogador', max_length=100),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='perna',
            field=models.CharField(choices=[('Destro', 'Destro'), ('Canhoto', 'Canhoto'), ('Ambidestro', 'Ambidestro')], db_column='perna_jogador', max_length=20),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='peso',
            field=models.DecimalField(blank=True, db_column='peso_jogador', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('Goleiro', 'Goleiro'), ('Zagueiro', 'Zagueiro'), ('Lateral Esquerdo', 'Lateral Esquerdo'), ('Lateral Direito', 'Lateral Direito'), ('Volante', 'Volante'), ('Meio-campista', 'Meio-campista'), ('Meia Atacante', 'Meia Atacante'), ('Ponta Esquerda', 'Ponta Esquerda'), ('Ponta Direita', 'Ponta Direita'), ('Centroavante', 'Centroavante')], db_column='posicao_jogador', max_length=50),
        ),
        migrations.AlterField(
            model_name='partida',
            name='competicao',
            field=models.ForeignKey(blank=True, db_column='id_competicao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.competicao'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data_hora',
            field=models.DateTimeField(db_column='data_hora_partida'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='id',
            field=models.CharField(db_column='id_partida', default=backend.models.generate_partida_id, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partida',
            name='local',
            field=models.CharField(blank=True, db_column='local_partida', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='mandante',
            field=models.ForeignKey(db_column='id_clube_mandante', on_delete=django.db.models.deletion.CASCADE, related_name='partidas_mandante', to='backend.clube'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='placar_mandante',
            field=models.IntegerField(db_column='placar_mandante_partida', default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='placar_visitante',
            field=models.IntegerField(db_column='placar_visitante_partida', default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='visitante',
            field=models.ForeignKey(db_column='id_clube_visitante', on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='backend.clube'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='clube',
            table='clube',
        ),
        migrations.AlterModelTable(
            name='competicao',
            table='competicao',
        ),
        migrations.AlterModelTable(
            name='desempenho',
            table='desempenho',
        ),
        migrations.AlterModelTable(
            name='escalacao',
            table='escalacao',
        ),
        migrations.AlterModelTable(
            name='gol',
            table='gol',
        ),
        migrations.AlterModelTable(
            name='jogador',
            table='jogador',
        ),
        migrations.AlterModelTable(
            name='partida',
            table='partida',
        ),
        migrations.RemoveField(
            model_name='desempenho',
            name='id',
        ),
        migrations.RemoveField(
            model_name='escalacao',
            name='clube',
        ),
        migrations.RemoveField(
            model_name='escalacao',
            name='id',
        ),
    ]
