# Generated by Django 5.2.11 on 2026-03-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_fix_user_clube_fk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='competicoes',
            field=models.ManyToManyField(blank=True, db_table='clube_competicao', related_name='clubes_inscritos', to='backend.competicao'),
        ),
    ]
