# Generated by Django 6.0.3 on 2026-03-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_desempenho_gols_contra'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalacao',
            name='tipo',
            field=models.CharField(choices=[('PADRAO', 'Padrão'), ('DEFENSIVA', 'Defensiva'), ('OFENSIVA', 'Ofensiva')], db_column='tipo_escalacao', default='PADRAO', max_length=20),
        ),
        migrations.RunSQL(
            sql='''
            DO $$
            BEGIN
                ALTER TABLE escalacao DROP CONSTRAINT IF EXISTS escalacao_pkey;
                ALTER TABLE escalacao
                    ADD CONSTRAINT escalacao_pkey PRIMARY KEY (id_partida, id_jogador, tipo_escalacao);
            END $$;
            ''',
            reverse_sql='''
            DO $$
            BEGIN
                ALTER TABLE escalacao DROP CONSTRAINT IF EXISTS escalacao_pkey;
                ALTER TABLE escalacao
                    ADD CONSTRAINT escalacao_pkey PRIMARY KEY (id_partida, id_jogador);
            END $$;
            ''',
        ),
        migrations.AlterField(
            model_name='escalacao',
            name='pk',
            field=models.CompositePrimaryKey('partida', 'jogador', 'tipo', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
