# Generated by Django 6.0.1 on 2026-01-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_clube_id_alter_competicao_id_alter_gol_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TREINADOR', 'Treinador')], default='ADMIN', max_length=10),
        ),
    ]
