# Generated by Django 5.1 on 2026-01-24 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_clube_id_alter_competicao_id_alter_gol_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desempenho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('gols', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='backend.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='backend.partida')),
            ],
            options={
                'verbose_name': 'Desempenho',
                'unique_together': {('partida', 'jogador')},
            },
        ),
    ]
